src/Entity/User.php
<?php

namespace App\Entity;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface,PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adress = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column]
    private ?int $telephone = null;

    /**
     * @var Collection<int, Commande>
     */
    #[ORM\OneToMany(targetEntity: Commande::class, mappedBy: 'no')]
    private Collection $Commande;

    /**
     * @var Collection<int, Avis>
     */
    #[ORM\OneToMany(targetEntity: Avis::class, mappedBy: 'user')]
    private Collection $user;

    /**
     * @var Collection<int, Cart>
     */
    #[ORM\OneToMany(targetEntity: Cart::class, mappedBy: 'user')]
    private Collection $carts;
#[ORM\Column(type: "text", nullable: true)]
private ?string $image_profile = null;
    

    #[ORM\Column]
    private bool $isVerified = false;

    public function __construct()
    {
        $this->Commande = new ArrayCollection();
        $this->user = new ArrayCollection();
        $this->carts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getRoles(): array
    {
        $roles =$this->roles;
        $roles[]='ROLE_USER';
       if($this->isVerified()){

 $roles[]='ROLE_VERIFIED';
       }
        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommande(): Collection
    {
        return $this->Commande;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->Commande->contains($commande)) {
            $this->Commande->add($commande);
            $commande->setNo($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->Commande->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getNo() === $this) {
                $commande->setNo(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(Avis $user): static
    {
        if (!$this->user->contains($user)) {
            $this->user->add($user);
            $user->setUser($this);
        }

        return $this;
    }

    public function removeUser(Avis $user): static
    {
        if ($this->user->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getUser() === $this) {
                $user->setUser(null);
            }
        }

        return $this;
    }

    public function eraseCredentials(): void
    {
        // Effacer les données sensibles si nécessaire
    }
    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    /**
     * @return Collection<int, Cart>
     */
    public function getCarts(): Collection
    {
        return $this->carts;
    }

    public function addCart(Cart $cart): static
    {
        if (!$this->carts->contains($cart)) {
            $this->carts->add($cart);
            $cart->setUser($this);
        }

        return $this;
    }

    public function removeCart(Cart $cart): static
    {
        if ($this->carts->removeElement($cart)) {
            // set the owning side to null (unless already changed)
            if ($cart->getUser() === $this) {
                $cart->setUser(null);
            }
        }

        return $this;
    }

    public function getImageProfile(): ?string
    {
        return $this->image_profile;
    }

    public function setImageProfile(?string $image_profile): static
    {
        $this->image_profile = $image_profile;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;
use App\Entity\Cart;
use App\Entity\User;
use App\Entity\Product;
use App\Entity\Commande;
use App\Entity\DetailCommande;
use Symfony\Component\Mime\Email;
use App\Repository\CartRepository;
use App\Repository\UserRepository;
use App\Repository\ImageRepository;
use App\Repository\ProductRepository;
use App\Repository\CommandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\DetailCommandeRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;


final class HomeController extends AbstractController
{
    #[Route('/home', name: 'app_home')]
public function index(
    Request $request,
    EntityManagerInterface $em,
    UserPasswordHasherInterface $hasher,
    ProductRepository $productRepo,
    ImageRepository $imageRepo // Ajout du repository pour les images
): Response {
    $user = $this->getUser();
    // Récupérer les derniers produits avec leurs images
    $lastProducts = $productRepo->findLastThreeProducts();
    
    // Optionnellement, récupérer toutes les images si nécessaire (ici cela dépend de la logique du projet)
    // $allImages = $imageRepo->findAll(); // Si tu veux toutes les images, mais cela peut être inutile

    return $this->render('home/pageAcceuil.html.twig', [
        'controller_name' => 'HomeController',
        'user' => $user,
        'lastProducts' => $lastProducts // Passer les produits avec images à la vue
    ]);
}

    
    #[Route('/contact', name: 'contact')]
    public function contact(): Response
    {
    return $this->render('home/contact.html.twig');
    }
    #[Route('/aboutus', name: 'about')]
    public function about(): Response
    {
    return $this->render('home/about.html.twig');
    }
    #[Route('/confirme', name: 'confirmation')]
    public function thankyou(): Response
    {
    return $this->render('home/thankyou.html.twig');
    }


    #[Route('/add/{id}', name: 'cart_add')]
#[IsGranted('IS_AUTHENTICATED_FULLY')]
public function add(Product $product, Request $request, EntityManagerInterface $em, CartRepository $cartRepo): Response
{
    $user = $this->getUser();
    $quantity = $request->query->get('quantity', 1); // quantité à ajouter, par défaut 1

    // Vérifier que le stock est suffisant AVANT d'ajouter au panier
    if ($product->getStock() < $quantity) {
        $this->addFlash('error', 'Stock insuffisant pour ce produit.');
        return $this->redirectToRoute('cart_show');
    }

    $cartItem = $cartRepo->findOneBy([
        'user' => $user,
        'product' => $product
    ]);

    if ($cartItem) {
        // Ici, on pourrait aussi vérifier que la quantité totale dans le panier ne dépasse pas le stock
        $newQuantity = $cartItem->getQuantity() + $quantity;
        if ($newQuantity > $product->getStock()) {
            $this->addFlash('error', 'Stock insuffisant pour ce produit avec la quantité demandée.');
            return $this->redirectToRoute('cart_show');
        }
        $cartItem->setQuantity($newQuantity);
    } else {
        $cartItem = new Cart();
        $cartItem->setUser($user);
        $cartItem->setProduct($product);
        $cartItem->setQuantity($quantity);
        $em->persist($cartItem);
    }

    // **On ne diminue PAS le stock ici**

    $em->flush();

    return $this->redirectToRoute('cart_show');
}


    #[Route('/show', name: 'cart_show')]
public function show(CartRepository $cartRepo): Response
{
    $user = $this->getUser();
    $cartItems = $cartRepo->findBy(['user' => $user]);

    $products = [];
    $total = 0;

    // Récupérer les produits du panier
    foreach ($cartItems as $item) {
        $product = $item->getProduct();
        $quantity = $item->getQuantity();
        $totalProduct = $product->getPrix() * $quantity;

        $products[] = [
            'product' => $product,
            'quantity' => $quantity,
            'total' => $totalProduct
        ];

        $total += $totalProduct; // Calculer le total du panier
    }

    return $this->render('home/cart.html.twig', [
        'products' => $products,
        'total' => $total // Passer le total à la vue
    ]);
}
#[Route('/remove/{id}', name: 'cart_remove')]
public function remove(Product $product, CartRepository $cartRepo, EntityManagerInterface $em): Response
{
    $user = $this->getUser();
    $cartItem = $cartRepo->findOneBy([
        'user' => $user,
        'product' => $product
    ]);

    if ($cartItem) {
        $quantity = $cartItem->getQuantity();

        // Rendre la quantité au stock
        $product->setStock($product->getStock() + $quantity);

        $em->remove($cartItem);
        $em->flush();
    }

    return $this->redirectToRoute('cart_show');
}

#[Route('/valider-commande', name: 'valider_commande')]
public function validerCommande(
    EntityManagerInterface $em,
    CartRepository $cartRepo
): Response {
    $user = $this->getUser();
    $cartItems = $cartRepo->findBy(['user' => $user]);

    if (empty($cartItems)) {
        $this->addFlash('error', 'Votre panier est vide.');
        return $this->redirectToRoute('cart_afficher');
    }

    // 1. Vérifier le stock pour chaque produit
    foreach ($cartItems as $item) {
        $produit = $item->getProduct();
        $quantite = $item->getQuantity();

        if ($produit->getStock() < $quantite) {
            $this->addFlash('error', "Stock insuffisant pour le produit : " . $produit->getName());
            return $this->redirectToRoute('cart_afficher');
        }
    }

    // 2. Créer la commande
    $commande = new Commande();
    $commande->setNo($user);
    $commande->setCreatedAt(new \DateTimeImmutable());
    $commande->setStatut('En attente');
    $montantTotal = 0;

    // 3. Créer les détails de la commande et diminuer le stock
    foreach ($cartItems as $item) {
        $produit = $item->getProduct();
        $quantite = $item->getQuantity();
        $prix = $produit->getPrix();

        // Diminuer le stock
        $produit->setStock($produit->getStock() - $quantite);

        $detail = new DetailCommande();
        $detail->setProduct($produit);
        $detail->setCommande($commande);
        $detail->setQuantite($quantite);
        $detail->setPrixUnitaire($prix);

        $em->persist($detail);

        $montantTotal += $prix * $quantite;
    }

    $commande->setMontantTotal($montantTotal);
    $em->persist($commande);

    // 4. Vider le panier
    foreach ($cartItems as $item) {
        $em->remove($item);
    }

    $em->flush();

    $this->addFlash('success', 'Commande validée avec succès !');
    return $this->redirectToRoute('confirmation');
}


#[Route('/email/{id}', name: 'email')]
public function email($id, UserRepository $userRepo, MailerInterface $mailer, CommandeRepository $cmd): Response
{
    $user = $userRepo->find($id);

    if ($user === null) {
        throw $this->createNotFoundException('Utilisateur non trouvé');
    }

    $firstname = htmlspecialchars($user->getFirstname(), ENT_QUOTES, 'UTF-8');

    $htmlContent = <<<HTML
    <div style="font-family: Arial, sans-serif; padding: 20px; background-color: #f8f9fa; color: #333;">
        <h2 style="color: #007bff;">Bonjour $firstname,</h2>
        <p>Votre commande a été <strong>validée avec succès</strong> !</p>
        <p>Merci pour votre confiance et votre achat.</p>
        <div style="margin-top: 20px; padding: 15px; background-color: #e9ecef; border-radius: 5px;">
            <p><strong>Numéro du livreur :</strong> <span style="font-size: 18px; color: #28a745;">93164748</span></p>
        </div>
        <p style="margin-top: 30px;">Cordialement,<br>L’équipe de livraison</p>
    </div>
    HTML;

    $email = (new Email())
        ->from('rahmabassou3@gmail.com')
        ->to($user->getEmail())
        ->subject('Confirmation de votre commande')
        ->html($htmlContent);

    try {
        $mailer->send($email);
        $this->addFlash('success', 'Email envoyé avec succès.');
    } catch (\Exception $e) {
        $this->addFlash('error', 'L\'envoi de l\'email a échoué : ' . $e->getMessage());
    }

    return $this->render('home/thankyou.html.twig');
}


#[Route('/commande/details', name: 'commande_details')]
public function showDetails(
    Request $request,
    CommandeRepository $commandeRepo,
    DetailCommandeRepository $detailRepo
): Response {
    $page = max(1, $request->query->getInt('page', 1));
    $limit = 3;

    $pagination = $commandeRepo->findPaginatedCommandes($page, $limit);

    if (!$pagination['data']) {
        throw $this->createNotFoundException('Aucune commande trouvée.');
    }

    $commandesAvecDetails = [];
    foreach ($pagination['data'] as $commande) {
        $details = $detailRepo->findBy(['commande' => $commande]);
        $commandesAvecDetails[] = [
            'commande' => $commande,
            'details' => $details,
        ];
    }

    return $this->render('dashboard/details.html.twig', [
        'commandesAvecDetails' => $commandesAvecDetails,
        'total' => $pagination['total'],
        'page' => $page,
        'limit' => $limit,
    ]);
}


}

templates/home/cart.html.twig
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Untree.co">
  <link rel="shortcut icon" href="favicon.png">

  <meta name="description" content="" />
  <meta name="keywords" content="bootstrap, bootstrap4" />

		<!-- Bootstrap CSS -->
		<link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
		<link href="{{ asset('css/tiny-slider.css') }}" rel="stylesheet">
		<link href="{{ asset('css/style.css') }}" rel="stylesheet">
		<title>Panier</title>
	</head>
{% include 'home/navbar.html.twig' %}
	<body>
		<!-- Start Hero Section -->
			<div class="hero">
				<div class="container">
					<div class="row justify-content-between">
						<div class="col-lg-5">
							<div class="intro-excerpt">
								<h1>Panier</h1>
							</div>
						</div>
					</div>
				</div>
			</div>

		<div class="container">
			<div class="row mb-5">
				<form class="col-md-12" method="post">
					<div class="site-blocks-table">
						<table class="table">
							<thead>
								<tr>
									<th class="product-thumbnail">Image</th>
									<th class="product-name">Produit</th>
									<th class="product-price">Prix</th>
									<th class="product-quantity">Quantité</th>
									<th class="product-total">Total</th>
									<th class="product-remove">Supprimer</th>
								</tr>
							</thead>
							<tbody>
							{% for item in products %}
								<tr>
									<td class="product-thumbnail">
										{% if item.product.getImage() is not empty and item.product.getImage()[0] is defined %}
											<img src="{{ item.product.getImage()[0].name }}" alt="Image" class="img-fluid" style="max-width: 100px;">
										{% else %}
											<img src="https://via.placeholder.com/100" alt="Pas d'image" class="img-fluid" style="max-width: 100px;">
										{% endif %}
									</td>
									<td class="product-name">
										<h2 class="h5 text-black">{{ item.product.name }}</h2>
									</td>
									<td class="product-price">{{ item.product.prix }} dt</td>
									<td>
										<div class="input-group mb-3">
											<h2 class="form-control text-center" >{{ item.quantity }}</h2>
										</div>
									</td>
									<td class="product-total">{{ item.total }} dt</td>
									<td>
										<a href="{{ path('cart_remove', {'id': item.product.id}) }}" class="btn btn-black btn-sm">Supprimer</a>
									</td>
								</tr>
							{% else %}
								<tr>
									<td colspan="6" class="text-center">Votre panier est vide</td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
				</form>
			</div>

			<div class="row justify-content-center">
				<div class="col-md-6">
					<div class="card mb-5">
						<div class="card-body">
							<div class="row mb-3">
								<div class="col-12">
									<h3 class="text-black h4 text-uppercase text-center mb-4">Total du panier</h3>
								</div>
							</div>
							<div class="row mb-2">
								<div class="col-6">
									<span class="text-black">Sous-total</span>
								</div>
								<div class="col-6 text-end">
									<strong class="text-black">{{ total|number_format(2, '.', ' ') }} dt</strong>
								</div>
							</div>
							<div class="row mb-2">
								<div class="col-6">
									<span class="text-black">Frais de livraison</span>
								</div>
								<div class="col-6 text-end">
									<strong class="text-black">Gratuit</strong>
								</div>
							</div>
							<hr>
							<div class="row mb-4">
								<div class="col-6">
									<span class="text-black fw-bold">Total TTC</span>
								</div>
								<div class="col-6 text-end">
									<strong class="text-black">{{ total|number_format(2, '.', ' ') }} dt</strong>
								</div>
							</div>
              {% if products is not empty %}
							<div class="row mb-3">
								<div class="col-12">
									<a href="{{ path('valider_commande') }}" class="btn btn-black btn-lg py-3 w-100">
										Confirmer la commande
									</a>
								</div>
							</div>
              {% endif %}
							<div class="row">
								<div class="col-12">
									<a href="{{ path('produit.index') }}" class="btn btn-outline-black btn-sm w-100">
										Continuer les achats
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="mt-5">
			{% include 'home/footer.html.twig' %}
		</div>
		<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
		{% for message in app.flashes('error') %}
<script>
    Swal.fire({
        icon: 'error',
        title: 'Erreur',
        text: '{{ message }}',
        confirmButtonColor: '#dc3545'
    });
</script>
{% endfor %}
		<script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
		<script src="{{ asset('js/tiny-slider.js') }}"></script>
		<script src="{{ asset('js/custom.js') }}"></script>

	</body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>/home/rahma/projetSymfony/src/Controller/HomeController.php</code></li>
        <li>Your template at <code>/home/rahma/projetSymfony/templates/home/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/home/navbar.html.twig
<style>
/* Styles généraux */
.dropdown-toggle {
    transition: all 0.2s;
}

.dropdown-toggle:hover {
    opacity: 0.8;
    transform: translateY(-1px);
}

.dropdown-menu {
    min-width: 220px;
    border: 1px solid rgba(255, 255, 255, 0.1);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
}

.navbar-dark .navbar-nav .nav-link {
    transition: color 0.3s ease;
    padding: 0.5rem 1rem;
}

.navbar-dark .navbar-nav .nav-link:hover {
    color: rgba(255, 255, 255, 0.9);
    transform: translateY(-1px);
}

/* Style pour l'image de profil */
.profile-image {
    object-fit: cover;
    border: 2px solid rgba(255, 255, 255, 0.3);
    transition: all 0.3s ease;
    width: 40px;
    height: 40px;
	
}

.profile-image:hover {
    border-color: rgba(255, 255, 255, 0.6);
    transform: scale(1.05);
}

/* Dropdown utilisateur amélioré */
.user-dropdown {
    margin-left: 1rem;
}

.user-dropdown .dropdown-toggle::after {
    margin-left: 0.5rem;
    vertical-align: middle;
}

.user-dropdown .dropdown-menu {
    padding: 0.5rem 0;
}

.user-dropdown .dropdown-item {
    padding: 0.5rem 1.5rem;
    transition: all 0.2s;
}

.user-dropdown .dropdown-item:hover {
    background-color: rgba(255, 255, 255, 0.1);
    padding-left: 1.75rem;
}

.user-dropdown .dropdown-header {
    padding: 0.5rem 1.5rem;
    font-weight: 500;
    color: #fff;
    white-space: nowrap;
}

.user-dropdown .dropdown-divider {
    border-color: rgba(255, 255, 255, 0.1);
    margin: 0.5rem 0;
}

/* Icône panier */
.cart-icon {
    height: 24px;
    transition: transform 0.3s ease;
}

.cart-icon:hover {
    transform: scale(1.1);
}

/* Responsive */
@media (max-width: 768px) {
    .profile-image {
        width: 36px;
        height: 36px;
	
    }
    
    .user-dropdown .dropdown-menu {
        margin-top: 0.5rem;
    }
	
}
</style>
<nav class="custom-navbar navbar navbar-expand-md navbar-dark bg-dark" aria-label="Furni navigation bar">
    <div class="container">
        <a class="navbar-brand" href="{{ path('app_home') }}">MyFurniture<span></span></a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsFurni">
            <ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ path('app_home') }}">Home</a>
                </li>
                <li>
                    <a class="nav-link" href="{{ path('produit.index') }}">Shop</a>
                </li>
                <li>
                    <a class="nav-link" href="{{ path('about') }}">About us</a>
                </li>
                <li>
                    <a class="nav-link" href="{{ path('contact') }}">Contact us</a>
                </li>

                {% if app.user %}
                    {% if 'ROLE_ADMIN' in app.user.roles %}
                        <li>
                            <a class="nav-link" href="{{ path('admin') }}">Dashboard</a>
                        </li>
                    {% elseif 'ROLE_CLIENT' in app.user.roles %}
                       
                    {% endif %}
                    <li>
                        <a class="nav-link" href="{{ path('cart_show') }}"><img src="{{ asset('images/cart.svg') }}" alt="Cart" style="height: 20px;"></a>
                    </li>
                {% else %}
                    <li>
                        <a class="nav-link" href="{{ path('app_login') }}">Login</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{path('app_register')}}">Register</a>
                    </li>
                {% endif %}
            </ul>

            {% if app.user %}
            <div class="dropdown ms-3">
                <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser" data-bs-toggle="dropdown" aria-expanded="false">
                    {% if app.user.imageProfile  %}
                <img src="{{app.user.imageProfile }}" alt="Profile" class="rounded-circle me-2" width="64" height="64" style="object-fit: cover;">

                    {% else %}
                 
                    {% endif %}
                    <span class="d-none d-sm-inline">{{ app.user.firstname }}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser">
                    <li><a  href="{{path('app_profil_edit')}}"class="dropdown-item">Edit Profil</a></li>
                    <li><hr class="dropdown-divider"></li>
                  
                    <li><a class="dropdown-item" href="{{ path('app_logout') }}">Sign out</a></li>
                </ul>
            </div>
            {% endif %}
        </div>
    </div>
</nav>